# Generated by Django 2.2.1 on 2019-07-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='firstapp',
        ),
    ]
