# Generated by Django 2.1.7 on 2019-08-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_beersnacks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beersnacks',
            new_name='Beer_snacks',
        ),
    ]
