# Generated by Django 2.1.7 on 2019-08-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_cocktail_snacks_ricewine_snacks_soju_snacks_whiskey_snacks_wine_snacks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Soju_snacks',
            new_name='Beer_snack',
        ),
        migrations.RenameModel(
            old_name='whiskey_snacks',
            new_name='Cocktail_snack',
        ),
        migrations.RenameModel(
            old_name='RiceWine_snacks',
            new_name='RiceWine_snack',
        ),
        migrations.RenameModel(
            old_name='Cocktail_snacks',
            new_name='Soju_snack',
        ),
        migrations.RenameModel(
            old_name='Beer_snacks',
            new_name='whiskey_snack',
        ),
        migrations.RenameModel(
            old_name='Wine_snacks',
            new_name='Wine_snack',
        ),
    ]
